config/routes.rb
CommandPost::Application.routes.draw do

  
 
  root :to => 'users#login'
  

  match "/home" => "home#index",as: :home
  match "/facades/edit" => "facades#edit"

  get "home/index"

  scope "users" do
    get 'login' => 'users#login',as: :login
    post 'logged_in' => 'users#logged_in',as: :logged_in
    delete 'logout' => 'users#logout',as: :logout
  end

  resources :users,except: [:login,:logged_in,:logout] do
    collection do
      post 'upload'
    end
  end
  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put
  resources  :sharetives
  
  resources :facades do
    match '/update/multiple' => 'facades#update_multiple', :on => :collection, :via => :put
    resources  :sharetives do
      match 'update/multiple' => 'sharetives#update_multiple', :on => :collection, :via => :put
    end
  end

  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put

end

app/models/user.rb
class User < ServiceObject
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  cattr_accessor :secret_key,:current_user
  # validate :email,:password,:first_name,:last_name,presence: true,if: :required?
  attr_reader :attributes
  attr_accessor :email,:id,:password,:access_token,:first_name,:last_name,:company,:lat,:lng,:access_token_timestamp,:access_token_expires_at,:flash_message,:roles,:access_controls,:poaster_instances

  VALID_ROLES = ["curator", "networker"]

  def initialize(attributes={})
    @attributes = attributes || {}
    build_attribute
  end

  def persisted?
    false
  end

  def valid?
    true
  end

  def access_controls
    ## For current user the access controls super would always be nil
    ## and we have to retrieve it
    @access_controls || self.class.retrieve_access_controls
  end

  def poaster_instances
    @poaster_instances || self.class.retrieve_poaster_instances
  end

  def company_id
    self.company[:id] || self.company["id"] rescue nil
  end

  def user_roles
    roles.map { |r| r.capitalize }.join(",")
  end

  def has_roles?(role)
    roles.find { |r| r.to_sym == role}
  end

  def reset_attributes
    build_attribute
  end

  def company_name
    company[:name]
  end  

  def save
    response = self.class.create_info(users: [as_json],path: '/api/v1/registrations.json',access_token: current_user.access_token,method: :post)
    if response.success?
      self.flash_message = "Successfully added #{self.full_name}"
      return true
    elsif response.failed?
      self.flash_message = response.errors
      return false
    end
  end

  def update_attributes(params)
    response = self.class.update_info(user: params,path: "/api/v1/users/#{id}.json",access_token: current_user.access_token,method: :put)
    if response.success?
      @attributes = response.data['user']
      reset_attributes
      self.flash_message = "Successfully updated #{self.full_name}"
      return true
    elsif response.failed?
      @attributes = params
      build_attribute
      self.flash_message = response.errors.join(' ')
      return false
    end
  end


  def destroy
    response = self.class.remove_info(path: "/api/v1/users/#{id}",access_token: current_user.access_token,method: :delete)
    if response.success?
      self.flash_message = "Successfully deleted #{self.full_name}"
      return true
    elsif response.failed?
      self.flash_message = response.errors
      return false
    end
  end

  def full_name
    [first_name,last_name].join(' ')
  end

  def build_attribute
    attributes.each do |attribute,value|
      send("#{attribute}=",value)
    end
  end

  def clean_up_password
    self.password = nil
  end

  def as_json
    {
      first_name: first_name,
      last_name: last_name,
      email: email,
      roles: roles,
      company_id: company_id
    }
  end


  class << self

    def has_valid_roles?(users)
      flag = true
      wrong_users = []
      users.each do |u|
        unless u[:roles] and VALID_ROLES.include?(u[:roles].downcase.strip)
          wrong_users << u[:first_name]
          flag = false
        end
      end
      current_user.flash_message = "Invalid role for #{wrong_users.join(', ')}" if not (wrong_users.blank? or wrong_users.empty?) and not flag
      return flag
    end

    def remove_special_chars(users)
      users.each do |u|
        u.each{|k, v| u[k] = u[k].strip.gsub("'", '') if not u[k].nil?}
      end
      return users
    end

    def find_and_save(file)
      ## Read CSV file
      if users = parse_csv_file(file)
        users = remove_special_chars(users)
        bulk_insert(users) if has_valid_roles?(users)
      end
    end

    def bulk_insert(users)
      response = create_info(users: users,path: '/api/v1/registrations.json',access_token: current_user.access_token,method: :post)
      if response.success?
        current_user.flash_message = 'Succesfully Uploaded the CSV File'
      else
        current_user.flash_message = response.errors
      end
    end

    def all
      response = fetch_info(path: '/api/v1/users',access_token: current_user.access_token)
      if response.success?
        users = response.data['users']
        build_object(users)
      else
        current_user.flash_message = response.errors
        nil
      end
    end

    def find_by_id(id)
      #fetch_info({:id =>  id,:path => '/',access_token: current_user.access_token})
      response = fetch_info(:path => "/api/v1/users/#{id}/edit",access_token: current_user.access_token,plain: true)
      if response.success?
        user = response.data['user']
        build_object(user)
      else
        current_user.flash_message = response.errors
        nil
      end
    end

    def find_by_token(token)
      reset_session(token)
      response = fetch_info(:path => "/api/v1/users/me.json",access_token: token,plain: true)
      if response.success?
        user = response.data['user']
        build_object(user)
      elsif response.failed?
        nil
        ## Dont throw warden over here lest you would get a cyclic call  :)
        #throw(:warden, :scope => :user, :message => response.errors)
      end
    end

    def reset_session(token)
      Store.del("users.#{token}")
    end

    def find(token)
      ## the find method is implicitly used for user object sigin
      build_from_store("users.#{token}") || find_by_token(token)
    end

    def authenticate(data={})
      response = fetch_info data.merge(path: '/api/v1/sessions.json',method: :post)
      if response.success?
        users = response.data['user']
        build_object(users)
      else
        throw(:warden,:message => response.errors.join)
      end
    end

    def retrieve_access_controls
      response = fetch_info(path: "/api/v1/users/#{current_user.id}/access_controls.json",access_token: current_user.access_token,plain: true)
      if response.success?
        response.data['access_controls']
      elsif response.failed?
        nil
      end
    end

    def retrieve_poaster_instances
      response = fetch_info(path: "/api/v1/users/#{current_user.id}/poaster_instances.json",access_token: current_user.access_token,plain: true)
      if response.success?
        response.data['poaster_instances']
      elsif response.failed?
        ## return nil because controller would throw and error for nil 
        nil
      end
    end

    private
    def build_object(users)
      case users
      when Array
        Rails.logger.info "******* User is - Array *****"
        users.map { |user| build_object(user) }
      when Hash
        Rails.logger.info "******* User is - Hash *****"
        new(users)
      end
    end

    def build_from_store(token)
      user = if (attributes = Store.find(token))
        build_object(attributes)
      else
        nil
      end
      user
    end

    def parse_csv_file(file)
      csv = CSVParser.new(file)
      status, msg = csv.validate_rows
      if status
        csv.to_hash
      else
        current_user.flash_message = msg
        return false
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_users,:only => [:index,:create,:new,:edit,:update]
  skip_before_filter :set_current_user,:only => [:login,:logged_in]
  prepend_before_filter :require_no_user ,:only => [:login,:logged_in]
  prepend_before_filter :require_user,:only => [:logout,:index,:new,:create,:edit,:update,:destroy]


  def index
    page = params[:page] || 1
    @users = Kaminari.paginate_array(@users).page(page).per(10)
  end

  def new
    @user = User.new
    @user.roles = [:curator]
  end

  def create
    @user = User.new(params[:user])
    @user.company = current_user.company
    if @user.valid? and @user.save
      flash[:alert] = @user.flash_message
      render 'new'
    else
      flash[:alert] = @user.flash_message.pop[:error].join(" ") if @user.flash_message.is_a?(Array)
      render 'new'
    end
  end

  def upload
    # if params[:users].present? and User.upload_csv
    if remotipart_submitted? and params[:user][:attachment]
      if User.find_and_save(params[:user][:attachment].tempfile)
        @msg = current_user.flash_message
        current_user.flash_message = nil
      else
        @msg = current_user.flash_message
      end
    else
      @msg = "Please select appropriate file."
    end

    respond_to do |format|
      format.js
    end
    ## Need to tackle all edge cases of file corrupted and other stuff
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user.nil? or current_user.flash_message.present?
      redirect_to home_path
      flash[:alert] = current_user.flash_message
    else
      render 'edit'
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user and @user.update_attributes(params[:user])
      flash[:alert] = @user.flash_message
      render 'edit'
    else
      flash[:alert] = @user.flash_message
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    if @user and @user.destroy
      flash[:alert] = @user.flash_message
      redirect_to users_path
    else
      flash[:alert] = @user.flash_message
    end
  end

  def login
    build_user
    render layout: 'site'
  end


  def logged_in
    authenticate!(auth_options)
    if logged_in?
      flash[:alert] = 'Sucessfully Loggedin'
      redirect_to  (stored_path || home_path)
    else
      build_user
      flash[:alert] = @user.flash_message
      render 'login',layout: 'site'
    end
  end

  def logout
    super
    flash[:alert] = 'Logout Successfully'
    redirect_to login_path
  end

  def access_controls
    current_user.access_controls
  end

  private

  def build_user
    @user = User.new(params[:user] || {})
    clean_up_password
  end

  def clean_up_password
    @user.clean_up_password
  end

  def auth_options
    {recall: "#{controller_path}#login" ,message: "Invalid Email or Password" }
  end

  def load_users
    @users = User.all || []
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def seperator
    " | "
  end
end

app/views/users/_user.html.erb
<tr>
  <td><label for=""><input type="checkbox"></label></td>
  <td><%= user.full_name %></td>
  <td><%= user.email %></td>
  <td><%= user.user_roles %></td>
  <td> 
    <%unless current_user.id == user.id %>
      <%= link_to "", edit_user_path(user.id), :class => "edit entypo-pencil" %>
      <%= link_to "",user_path(user.id),method: :delete,confirm: 'Are you Sure',:class => "delete entypo-trash" %>
    <%end%>
  </td>
</tr>

app/views/users/edit.html.erb
  <div id="appContainer" class="addAccountContainer clearfix">
    <strong id="usersCount" class="entypo-users">
      <%= link_to "#{@users.count} users",users_path %> / Edit Users
    </strong>
  </div>
  <%= form_for(@user, url: user_path(@user.id),method: :put) do |f| %>
    <div class="accountGroup">
      <div class="inputGroup errorGroup clearfix">
        <strong>&nbsp;</strong>
        <div class='inputHolder'> </div>
      </div>
      <div class="inputGroup clearfix">
        <strong>User Information</strong>
        <div class='inputHolder'>
          <div class="input-group split">
            <label for="firstName">First Name</label>
            <%= f.text_field :first_name %>
          </div>
          <div class="input-group split lastChild">
            <label for="lastName">Last Name</label>
            <%= f.text_field :last_name %>
          </div>
          <div class="input-group">
            <label for="EmailAddress">Email Address</label>
            <%= f.text_field :email %>
          </div>
        </div>
      </div>
      <div class="inputGroup clearfix">
        <strong>Role</strong>
        <div class="inputHolder clearfix">
          <div id="roleSelector" class="input-group">
            <div class="radioGroup">
              <span class="fontawesome-circle">
                <%= radio_button_tag 'user[roles][]',"curator",@user.roles.include?("curator") %>
              </span>
              <label for="curator">Curator</label>
            </div>
            <div class="radioGroup">
              <span>
                <%= radio_button_tag 'user[roles][]',"networker",@user.roles.include?("networker") %>
              </span>
              <label for="networker">Networker</label>
            </div>
          </div>
        </div>
      </div>
      <div class="inputGroup clearfix">
        <div class="input-group">
          <%= link_to 'Cancel',users_path,:class => 'cancel'%>
          <%= f.submit "Save Information",:class => 'curvyBtn' %>
        </div>
      </div>
    </div>
  <%end%>

<script type="text/javascript">
  $(document).ready(function() {
    $('.radioGroup input:radio').click(function(){
      if( $(this).is(':checked') ) {
        $('.radioGroup > span').removeClass('fontawesome-circle');
        $(this).parent('span').addClass('fontawesome-circle');
      }
    });

    $("input:radio:checked").trigger("click");
  });
</script>

app/views/users/index.html.erb
<div class="clearfix" id="userListHeader">
  <div id="userListActions">
    <a href="#" class="entypo-export greyBtn" id="exportUsers">Export</a>
    <%= link_to 'Add User' , new_user_path, :class => 'curvyBtn entypo-plus-circled', :id => 'addUser' %>
  </div>
  <div id="userListTasks">
    <strong id="usersCount" class="entypo-users"><span><%= @users.count %></span> users</strong>
    <input type="text" placeholder="Search...">
    <a href="#" id="filter" class="fontawesome-filter"></a>
    <div class="pagination">
      <%= link_to_previous_page @users, '', :class => 'entypo-left-open-big' %>
      <%= link_to_next_page @users, '', :class => 'entypo-right-open-big' %>
    </div>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th><label for=""><input type="checkbox"></label></th>
      <th>Name</th>
      <th>Email / Username</th>
      <th>Role</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

<script type="text/javascript">
  $('input:checkbox').click(function(){
    if( $(this).is(':checked') ) {
      $(this).parent('label').addClass('entypo-check');
    } else {
      $(this).parent('label').removeClass('entypo-check');
    }
  });
</script>

app/views/users/login.html.erb
<div class="formWrapper signIn">
  <%= image_tag("logo.png", alt: "Poaster", id: "signInLogo") %>
  <%= form_for(@user, url: logged_in_path,method: :post) do |f| %>
    <%= render 'flash_notifications' %>

    <%= f.text_field :email, :placeholder => "Email" %>
    <%= f.password_field :password, :placeholder => "Password" %>

  <div class="actions">
    <%= f.submit 'SIGN IN' %>
  </div>
  <% end %>

  <span class="formNote">Don't have an account? <a href="#">Sign up</a></span>
</div>

app/views/users/new.html.erb
  <div id="appContainer" class="addAccountContainer clearfix">
    <strong id="usersCount" class="entypo-users">
      <%= link_to "#{@users.count} users",users_path %> / Add Users
    </strong>
    <span id="csvUpload">OR <%= link_to 'Import with CSV' ,'#csvModal' %></span>
  </div>
  <%= form_for(@user, url: users_path,method: :post) do |f| %>
    <div class="accountGroup">
      <div class="inputGroup errorGroup clearfix">
        <strong>&nbsp;</strong>
        <div class='inputHolder'> </div>
      </div>
      <div class="inputGroup clearfix">
        <strong>User Information</strong>
        <div class='inputHolder'>
          <div class="input-group split">
            <label for="firstName">First Name</label>
            <%= f.text_field :first_name %>
          </div>
          <div class="input-group split lastChild">
            <label for="lastName">Last Name</label>
            <%= f.text_field :last_name %>
          </div>
          <div class="input-group">
            <label for="EmailAddress">Email Address</label>
            <%= f.text_field :email %>
          </div>
        </div>
      </div>
      <div class="inputGroup clearfix">
        <strong>Role</strong>
        <div class="inputHolder clearfix">
          <div id="roleSelector" class="input-group">
            <div class="radioGroup">
              <span class="fontawesome-circle">
                <%= radio_button_tag 'user[roles][]',"curator",@user.roles.include?("curator") %>
              </span>
              <label for="curator">Curator</label>
            </div>
            <div class="radioGroup">
              <span>
                <%= radio_button_tag 'user[roles][]',"networker",@user.roles.include?("networker") %>
              </span>
              <label for="networker">Networker</label>
            </div>
          </div>
        </div>
      </div>
      <div class="inputGroup clearfix">
        <strong><%= link_to '+ Add another user','#',:id => "addAnotherUser"%></strong>
        <div class="input-group">
          <%= link_to 'Cancel',users_path,:class => 'cancel'%>
          <%= f.submit "Save Information",:class => 'curvyBtn' %>
        </div>
      </div>
    </div>
  <%end%>

<div class="app-modal" id="csvModal" style="display: none;">
  <div class="app-modal-header clearfix">
    <a href="#" class="close-modal">Close</a>
    <h1>Import CSV file</h1>
  </div>
  <span class="uploadSpan">
    <div class="app-modal-body">
      <div class="uploadForm">
        <img src="/assets/csv.png" alt="CSV">
        <span>Click an icon above to Browse/Select<br>file from your Computer.</span>
        <%= form_tag upload_users_path ,:method => :post ,:id => 'importUsers',multipart: true, :remote => true do  %>
          <%= file_field_tag 'user[attachment]' ,:id => 'csvInput' %>
          <%= submit_tag 'Submit',:class => 'none submit_me' %>
        <%end%>
      </div>
      <strong id="fileName"></strong>
    </div>
    <div class="app-modal-footer">
      <a href="#" class="curvyBtn">Upload File</a>
    </div>
  </span>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('.radioGroup input:radio').click(function(){
      if( $(this).is(':checked') ) {
        $('.radioGroup > span').removeClass('fontawesome-circle');
        $(this).parent('span').addClass('fontawesome-circle');
      }
    });

    $("span.fontawesome-circle").find("input[type=radio]").trigger("click");

    var fileInput = $('#csvInput');
    $('.uploadForm img').click(function(){
      $('#csvInput').trigger('click');
    });

    $('#csvInput').change(function(){
      $('#fileName').append($(this).val().slice(12));
    });

    $('a[href="#csvModal"]').click(function(){
      $('span.uploadSpan ul.form_error').text('')
      $('span.uploadSpan ul.form_error').removeClass("form_error")
    })

    $('a[href="#csvModal"]').leanModal({ closeButton: ".close-modal" });

    $("a.curvyBtn").bind('click',function(event) {
      event.preventDefault();
      $('form#importUsers').submit()
    })

    //reloaded the page on close of modal because the file chosen to upload remained the same even after changing it.
    $(".close-modal").on("click", function () {
      location.reload()
    });
  });
</script>

app/views/users/upload.js.erb
<%= remotipart_response do %>
  $('a.curvyBtn').hide()
  $('span.uploadSpan ul.form_error').text('')
  $('span.uploadSpan ul.form_error').removeClass("form_error")
  var errors = $('<ul class="form_error">');
  <% if @msg.is_a?(Array) %>
    <% @msg.each do |m|%>
      <% m["error"] = m["error"].first.gsub('Email', m['email']) %>
      errors.append('<li><%= escape_javascript(m["error"]) %></li>')
    <% end %>
  <% else %>
    errors.append('<li><%= escape_javascript(@msg) %></li>')
  <% end %>
  errors.append('</ul>')
  $('span.uploadSpan').prepend(errors);
  $('a.curvyBtn').show()
<% end %>