config/routes.rb
CommandPost::Application.routes.draw do

  
 
  root :to => 'users#login'
  

  match "/home" => "home#index",as: :home
  match "/facades/edit" => "facades#edit"

  get "home/index"

  scope "users" do
    get 'login' => 'users#login',as: :login
    post 'logged_in' => 'users#logged_in',as: :logged_in
    delete 'logout' => 'users#logout',as: :logout
  end

  resources :users,except: [:login,:logged_in,:logout] do
    collection do
      post 'upload'
    end
  end
  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put
  resources  :sharetives
  
  resources :facades do
    match '/update/multiple' => 'facades#update_multiple', :on => :collection, :via => :put
    resources  :sharetives do
      match 'update/multiple' => 'sharetives#update_multiple', :on => :collection, :via => :put
    end
  end

  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put

end

app/models/sharetive.rb
class Sharetive
  include Mongoid::Document
  include Mongoid::Timestamps
  field :position,type: Integer
  field :sharetive,type: String
  field :sharetive_type,type: String
  field :video_url,type: String
  field :name,type: String
  field :description,type: String
  field :company_id,type: Integer
  before_validation :determine_sharetive_type
  #validate :valid_video_id,:if => :valid_condition?
  belongs_to :facade
  scope :for_company,lambda { |company_id| where(company_id: company_id)}
  mount_uploader :sharetive,SharetiveUploader

  index({position: 1})
  index({sharetive_type:1})

  def as_json
    json_hash =  {
      position: self.position,
      sharetive_type: self.sharetive_type,
      name: self.name,
      facadeId: self.facade_id.to_s,
      id: self._id.to_s,
      video_id: self.video_id,
    }

    if image?
      json_hash[:sharetive_url] = self.sharetive.url
    else
      json_hash[:sharetive_url] = self.video_url
    end
    json_hash
  end


  def video_id
    video_url =~ /watch\?v=(.+)/ 
    $1
  end

  def image?
    sharetive_type == 'image'
  end

  def video?
    sharetive_type == 'video'
  end

  private
  def valid_video_id
    self.errors.add(:video_url,'Not a valid url') unless video_url =~ /watch\?v=(.+)/
  end

  def valid_condition?
    self.video_url.present? and self.video?
  end

  def determine_sharetive_type
    self.sharetive_type = 
      if self.video_url.present? 
        'video'
      elsif  self.sharetive.present?
        'image'
      end 
  end  
end
Sharetive.create_indexes

app/controllers/sharetives_controller.rb
class SharetivesController < ApplicationController
  before_filter :load_facade, :except => [:update_all,:edit,:update]
  before_filter :load_sharetive, :only => [:edit,:destroy,:update,:show, :update_multiple]
  prepend_before_filter :require_user


  #http://localhost:3002/facades/52aad08c2559dfac24000009/sharetives.json
  ######################################################################
  # Response {
  #             "request_status":"success",
  #             "data":
  #                     [
  #                       {"position":1,"sharetive_type":"image",
  #                        "name":"Golf Course",
  #                        "facade_id":"52aad08c2559dfac24000009",
  #                         "sharetive_url":"https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd0a2559df0770000006/Club_Corp.jpeg?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=TQU7nWkOvLi8tcPr4MhznELhUq4%3D&Expires=1386930513"
  #                        },
  #                        {"position":2,
  #                        "sharetive_type":"image",
  #                         "name":"Second",
  #                         "facade_id":"52aad08c2559dfac24000009",
  #                         "sharetive_url":"https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd6d2559df0770000008/Screen_Shot_2013-10-01_at_1.12.16_AM.png?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=20BAnpYdKBlTW81iSRXF5wO87vw%3D&Expires=1386930513"
  #                         }
  #                     ]
  #          }
  ######################################################################
  def index
    respond_to do |format|
      @sharetives = @facade.sharetives.entries

      format.html {}
      format.json {
        response_hash = {
            request_status: :success,
            data: @sharetives.as_json
        }
        render :json => response_hash, :status => :ok
      }
    end
  end

  def show
  end

  def new
    @sharetive = @facade.sharetives.build
  end

  # POST http://localhost:3002/facades/52aad08c2559dfac24000009/sharetives.json
  ######################################################################
  #
  # "sharetive"=>
  #  {
  #     "name"=>"Sharetive - 11",
  #     "position"=>"4",
  #     "sharetive_type"=>"image",
  #     "video_url"=>"",
  #     "sharetive"=> <File Contents>
  #   }
  #
  #  Response
  #  {
  #    "request_status": "success",
  #    "data": {
  #              "position":2,
  #             "sharetive_type": "image",
  #             "name": "Second",
  #             "facade_id": "52aad08c2559dfac24000009",
  #             "sharetive_url": "https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd6d2559df0770000008/Screen_Shot_2013-10-01_at_1.12.16_AM.png?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=cEwuB7p5gtAWYcTixQkDx%2BPd8f4%3D&Expires=1387278229
  #
  #  }
  #
  ######################################################################

  def create
    @sharetive = @facade.sharetives.new(params[:sharetive])
    @sharetive.company_id = current_user.company_id
    respond_to do |format|
      if @sharetive.with({safe: true}).save

        format.html{
          flash[:alert] = 'Successfully created sharetives'
          redirect_to '/facades/#shareatives'
        }

        format.json {
          response_hash = {request_status: :success, data: @sharetive.as_json}
          render json: response_hash, status: :ok
        }
      else
        format.html {
          render 'new'
        }

        format.json {
          response_hash = {request_status: :failure,
                           data: nil,
                           errors: @sharetive.errors.full_messages}
          render json: response_hash, status: :ok
        }
      end
    end

    # Ajax code for sharetive create please add data-remote=true for ajax in modal form
    # @sharetive = @facade.sharetives.new(params[:sharetive])
    # @sharetive.company_id = current_user.company_id
    # respond_to do |format|
    #   format.js do 
    #     if @sharetive.with({safe: true}).save
    #       @success = true
    #       @response_hash = {request_status: :success, data: [@sharetive.as_json]}
    #     else
    #       @success = false
    #       @response_hash = {request_status: :failure,data: nil,errors: @sharetive.errors.full_messages}
    #     end
    #   end   
    # end 
  end

  def edit
    @facades = Facade.for_company(current_user.company_id)
    respond_to do |format|
      format.js
    end  
  end

  # PUT http://localhost:3002/facades/52aad08c2559dfac24000009/sharetives/52aadd6d2559df0770000008.json
  ######################################################################
  #
  # "sharetive"=>
  #               {
  #                 "position": 3,
  #                 "name": 'New Name'
  #               }
  #  Response
  #  {
  #    "request_status": "success",
  #    "data": {
  #              "position":3,
  #             "sharetive_type": "image",
  #             "name": "New Name",
  #             "facade_id": "52aad08c2559dfac24000009",
  #             "sharetive_url": "https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd6d2559df0770000008/Screen_Shot_2013-10-01_at_1.12.16_AM.png?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=cEwuB7p5gtAWYcTixQkDx%2BPd8f4%3D&Expires=1387278229
  #
  #  }
  #
  ######################################################################
  def update
    respond_to do |format|
      if @sharetive.with({safe: true}).update_attributes(params[:sharetive])

        format.html {
         flash[:alert] = 'Successfully updated sharetives'
         redirect_to facades_path
        }

        format.json {
          response_hash = {request_status: :success, data: [@sharetive.as_json]}
          render json: response_hash, status: :ok
        }
      else
        format.html {
          render 'edit'
        }

        format.json {
          response_hash = {request_status: :failure,
                           data: nil,
                           errors: @sharetive.errors.full_messages}
          render json: response_hash, status: :ok
        }
      end
    end
    ## Ajax code for sharetive please a data-remote true in  modal
    # respond_to do |format|
    #   format.js do 
    #     if @sharetive.with({safe: true}).update_attributes(params[:sharetive])
    #       @success = true
    #       @response_hash = {request_status: :success, data: [@sharetive.as_json]}
    #     else
    #       @success = false
    #       @response_hash = {request_status: :failure,data: nil,errors: @sharetive.errors.full_messages}
    #     end
    #   end   
    # end 
  end

  # PUT http://localhost:3002/facades/52aad08c2559dfac24000009/sharetives/update/multiple.json
  ######################################################################
  #
  # "sharetives"=>
  #               [{
  #                 "id": "52aadd6d2559df0770000008",
  #                 "position": 3,
  #                 "name": 'New Name'
  #               },
  #                {
  #                 "id": "52aadd0a2559df0770000006",
  #                 "position": 1,
  #                 "name": 'test 1'
  #                }]
  #  Response
  #  {
  #    "request_status": "success",
  #    "update_success_count": "2"
  #    "data": [
  #               {:position=>1,
  #                :sharetive_type=>"image",
  #                :name=>"Golf Course",
  #                :facade_id=>"52aad08c2559dfac24000009",
  #                :sharetive_url=>"https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd0a2559df0770000006/Club_Corp.jpeg?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=4XVEAA4jArnXTPVBrVW3G4Ge%2BG8%3D&Expires=1387278864"
  #               },
  #               {
  #                 :position=>2,
  #                 :sharetive_type=>"image",
  #                 :name=>"Second",
  #                 :facade_id=>"52aad08c2559dfac24000009",
  #                 :sharetive_url=>"https://poaster.s3.amazonaws.com/uploads/sharetive/sharetive/52aadd6d2559df0770000008/Screen_Shot_2013-10-01_at_1.12.16_AM.png?AWSAccessKeyId=AKIAJQWK7V4DKTHYWXDA&Signature=UxT20GeNi7SxGsF4aemgxgdqIWk%3D&Expires=1387278864"
  #               }
  #             ]
  #   }
  #
  ######################################################################


    # {
    #  "shareatives" => [
    #          {
    #            "id" => "3",
    #            "facadeId" => "2",
    #            "position" => "4"
    #          }
    #  ]
    # }

  def update_all
    @errors = []
    respond_to do |format|
      if valid_params? and store_shareatives and has_saved?  
        format.html{
          flash[:alert] = 'Successfully updates sharetives'
          redirect_to facades_path
        }

        format.json {
          response_hash = {
            request_status: :success,
            update_success_count: params[:shareatives].count
          }
          render json: response_hash, status: :ok
        }
      else
        format.html{
          flash[:alert] = 'Failed to update'
          redirect_to facades_path
        }

        format.json {
          response_hash = {
            request_status: :failure,
            errors: @errors
          }
          render json: response_hash, status: :ok
        }
      end  
    end
  end

  def update_multiple
    @sharetives = []

    params[:sharetives].each do |_sharetive|
      sharetive = @facade.for_company(current_user.company_id).
          where('sharetives._id' => _sharetive[:id] ).last

      next if sharetive.nil?
      sharetive.position = sharetive[:position].to_i
      @sharetives.push(sharetive) if sharetive.with({safe:true}).save
    end

    respond_to do |format|
      format.html{
        flash[:alert] = 'Successfully deleted sharetives'
        redirect_to facade_sharetives_path(@facade)
      }

      format.json {
        response_hash = {request_status: :success,
                        data: @sharetives.as_json,

app/helpers/sharetives_helper.rb
module SharetivesHelper
end

app/views/sharetives/_edit_sharetive.erb
<div class="app-modal" id="editShareativeModal" style="display: none;">
<!-- Uncomment the below for ajax call
 <%#=# form_for @sharetive,remote: true,:html => {:class => 'remote_me',multipart: true ,:id => "addNewShareativeForm" } do |f| %> -->

  <%= form_for @sharetive,:html => {:class => 'remote_me',multipart: true ,:id => "addNewShareativeForm" } do |f| %>
    <div class="app-modal-header clearfix">
      <a href="#" class="close-modal">Close</a>
      <h1>Edit Shareative  <%= @sharetive.name %></h1>
    </div>
    <span class="uploadSpan">
      <div class="app-modal-body">
        <div class="inputGroup clearfix">
          <div class='inputHolder'>
            <div class="input-group sideBySide">
              <label for="Facade">Add to Facade</label>
              <%= f.collection_select :facade_id,@facades,:id,:name,id: 'edit_facade_id',:class  => 'listOfFacades' %>
            </div>
            <div class="input-group">
              <label for="facadeTitle" >Title</label>
              <%= f.text_field :name, id: 'edit_facadeTitle' %>
            </div>
            <div class="input-group">
              <label for="Description">Description</label>
              <%= f.text_area :description, id: 'edit_facadeDescription' %>
            </div>
            <div class="input-group">
              <label for="youtubeURL">YouTube URL</label>
              <%= f.text_field :video_url, id: 'edit_youtubeURL' %>
            </div>
            <strong> OR </strong>
            <br/>
            <br/>
            <div class="input-group sideBySide lastChild">
              <label for="uploadThumb">Upload Thumbnail</label>
              <div class="sideGroup uploadVideoThumbGroup">
                <a id="edit_uploadVideoThumb">Click to upload a thumbnail for the image</a>
                <%= f.file_field :sharetive, id: 'edit_fileInput' %>
              </div>
              <%= f.hidden_field :sharetive_cache %>
            </div>
          </div>
        </div>
      </div>    
      <div class="app-modal-footer">
        <%= f.submit 'Update',:class => 'publishBtn' %>
        <a class="deleteShareative redBtn" data-sid="<%= @sharetive.id %>" data-fid="<%= @sharetive.facade_id %>">Delete</a>
        <a href="#" class="close-modal">Cancel</a>
      </div>
    </span>
  <% end %>
</div>
<a href="#editShareativeModal" style='display:none;' class='editModaltriggger'></a>
<script> 
 var fileInput = $('#edit_fileInput');
  $('#edit_uploadVideoThumb').click(function(){
    fileInput.trigger('click');
  });
</script>  

app/views/sharetives/create.js.erb
<% if @success %>
  var addedShartive = <%= @sharetive.as_json.to_json.html_safe %>
  $('#shareativesContainerInner').append(renderShareative(addedShartive))
  hideModal($('#newShareativeModal'));
<%else%>
  alert('failed')
<%end%>

app/views/sharetives/edit.html.erb
<h1>Sharetives#edit</h1>
<p>Find me in app/views/sharetives/edit.html.erb</p>

app/views/sharetives/edit.js.erb
<%= render 'edit_sharetive',layout: false %>

app/views/sharetives/index.html.erb
<h1>Sharetives#index</h1>
<table>
  <thead>
    <tr>
      <th> Name </th>
      <th> Order </th>
      <th> Type </th>
    </tr>
  </thead>
  <tbody>
    <% @sharetives.each do |sharetive| %>
    <tr>
      <td> <%= link_to sharetive.name,facade_sharetive_path(@facade,sharetive) %></td>
      <td> <%= sharetive.position %>
      <td> <%= sharetive.sharetive_type %>
    </tr>
    <%end%>
  </tbody>
</table>

app/views/sharetives/new.html.erb
<%= form_for([@facade,@sharetive],:multipart => true) do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <br/>

  <div>
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <br/>

  <div>
    <%= f.label :sharetive_type %>
    <%= f.select :sharetive_type,options_for_select([['image','image'],['video','video']]) %>
  </div>
 <br/>
  <div>
    <%= f.label :video_url %>
    <%= f.text_field :video_url %>
  </div>
   <br/>
  <div>
     <%= f.file_field :sharetive %>
  </div>
  <br/>
  <div>
    <%= f.submit  :submit %>
  </div>
<%end%>

app/views/sharetives/show.html.erb
<% if @sharetive.sharetive_type == "images" %>
  <%= image_tag @sharetive.sharetive %>
<%else%>
  <%= @sharetive_video_id %>
  <iframe id="ytplayer" type="text/html" width="300" height="168.75"
src="https://www.youtube.com/embed/<%= @sharetive.video_id %>?autoplay=0&showinfo=0"
frameborder="0" allowfullscreen>
<%end%>

app/views/sharetives/update.html.erb
<h1>Sharetives#update</h1>
<p>Find me in app/views/sharetives/update.html.erb</p>

app/views/sharetives/update.js.erb
<% if @success %>
  var editedShartive = <%= @sharetive.as_json.to_json.html_safe %>
  var selectSharetive = "div#shareativeId-"+editedShartive.id; 
  console.log(selectSharetive);
  $(selectSharetive).replaceWith(renderShareative(editedShartive))
  hideModal($('#editShareativeModal'));
<%else%>
  alert('failed')
<%end%>