config/routes.rb
CommandPost::Application.routes.draw do

  
 
  root :to => 'users#login'
  

  match "/home" => "home#index",as: :home
  match "/facades/edit" => "facades#edit"

  get "home/index"

  scope "users" do
    get 'login' => 'users#login',as: :login
    post 'logged_in' => 'users#logged_in',as: :logged_in
    delete 'logout' => 'users#logout',as: :logout
  end

  resources :users,except: [:login,:logged_in,:logout] do
    collection do
      post 'upload'
    end
  end
  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put
  resources  :sharetives
  
  resources :facades do
    match '/update/multiple' => 'facades#update_multiple', :on => :collection, :via => :put
    resources  :sharetives do
      match 'update/multiple' => 'sharetives#update_multiple', :on => :collection, :via => :put
    end
  end

  match '/sharetives/update_all' => 'sharetives#update_all', :via => :put

end

app/controllers/application_controller.rb
## Require this in application controller since the httparty lazy load
class ApplicationController < ActionController::Base
  protect_from_forgery
  # before_filter :authenticate_user!
  before_filter :set_current_user
  rescue_from Exception, with: :render_internal_server_error


  private
  def require_user
    unless current_user
      flash[:alert] = 'You must be logged in to access that page'
      store_location!
      redirect_to login_path
      return false
    end
  end

  def require_no_user
    if current_user
      flash[:alert] = 'You must be logged out to access that page'
      redirect_to home_path #|| request.referrer
      return false
    end
  end

  def store_location!
    session[:return_to] = return_to_path if request.get?
  end

  def stored_path
    session.delete(:return_to)
  end

  def return_to_path
    request.path_info
  end

  def set_current_user
    if current_user
      ## use current thread mechanism
      #Thread[:current]
      ## Need this to pass the token in the
      User.current_user = current_user
    end
  end

  def render_internal_server_error
    if request.format.json?
      render :json => {request_status: :failure }, :status => :internal_server_error
    else 
      raise
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def separator
    " | "
  end

  def flash_message
    if current_user
      current_user.flash_message
    end
  end

  def active_css_class(active_class)
    if active_class == controller_classes[controller_name]
      return 'current'
    end         
  end

  def controller_classes
    @css_mapper ||= {
      "users#index" => "users",
      "users#new" => "users",
      "users#create" => "users",
      "users#edit" => "users",
      "users#update" => "users",
      "users#destroy" => "users",
      "facades#index" => "facades",
      "facades#create" => "facades",
      "facades#new" => "facades",
      "facades#edit" => "facades",
      "facades#update" => "facades",
      "facades#destroy" => "facades",
      "sharetives#index" => "facades",
      "sharetives#create" => "facades",
      "sharetives#new"  => "facades",
      "sharetives#edit" => "facades",
      "sharetives#destroy" => "facades"
    }
    return @css_mapper
  end

  def controller_name
    [controller.controller_name,controller.action_name].join("#") 
  end

  def alert_list(alert_type)
    "#{alert_type}List"
  end

  def alert_box(alert_type)
    "#{alert_type}Box"
  end
end

app/views/application/_alert_message.html.erb
<% [:alert,:success,:notice,:error].each do |alert_type| %>
  <% if flash[alert_type] %>
    <div class=<%= alert_type.to_s %>>
      <span><%= flash[alert_type] %> </span>
    </div>
  <%end%>
<%end%>

app/views/application/_flash_notifications.html.erb
<% if flash[:alert].present? %>
<div class="messageWrapper clearfix">
  <div class="messageIcon"><span class="entypo-attention"></span></div>
  <div class="alertBox">
     <ul class="alertList">
        <li><%= flash[:alert] || flash_message %></li>
     </ul>
  </div>
</div>
<%end%>

app/views/application/_footer.html.erb
<div id="footer" class="clearfix">
  <p>Poaster.mobi - 2013. 20 N Wacker Drive, Suite 3330, Chicago, IL 60606</p>
  <a href="#">ABOUT US</a>
  <a href="#">CONTACT</a>
  <a href="#">SUPPORT</a>
  <a href="#">TERMS</a>
</div>

app/views/application/_header.html.erb
<div id="appHeader" class="clearfix">
  <%= link_to image_tag("logo.png"), '/', :id => 'brand' %>
</div>
<div id="pageHeader">
  <h1>Command Poast</h1>
  <ul id="appTabs">
    <li><%= link_to 'INSIGHTS', '#',:class => "#{active_css_class('insights')} entypo-chart-pie" %></li>
    <li><%= link_to 'ANALYTICS','#',:class => "#{active_css_class('analytics')} entypo-chart-line" %></li>
    <li><%= link_to 'CONTENT',facades_path,:class => "#{active_css_class('facades')} fontawesome-file" %></li>
    <li><%= link_to 'USERS',users_path,:class => "#{active_css_class('users')} entypo-users" %></li>
  </ul>
</div>

app/views/application/_menu_bar.html.erb
<div class="profileDetail">
  <div class="profileName">
    <strong class="name"><%= current_user.full_name %></strong>
    <span class="entypo-down-dir"></span>
    <span class="org"><%= current_user.company["name"].capitalize %></span>
  </div>
  <div class="list">
    <a href="#">Settings</a>
    <%= link_to "Sign out",logout_path,method: :delete %>
  </div>
</div>